language: node_js

node_js:
  - "6.9"
  - "7.2"
services:
  - rabbitmq
  - mongodb

before_script:
  - sudo rabbitmq-plugins enable rabbitmq_stomp
  - sudo service rabbitmq-server restart
  - sudo rabbitmqctl status
  - sudo rabbitmq-plugins list

cache:
  directories:
  - node_modules
git:
  depth: 3
after_script:
  - yarn report-coverage

notifications:
  slack: eliftech:rXNsG1csijJulkvTRPzVDU3w
