language: node_js

# Sudo: false should make the builds faster, but collides with rabbitmq
sudo: true

dist: trusty

node_js:
  - "4.6"
  - "6.9"
  - "7.2"
services:
  - rabbitmq
  - mongodb

cache:
  directories:
  - node_modules
git:
  depth: 3
after_script:
  - yarn report-coverage
