language: node_js

node_js:
  - "6.9"
  - "7.2"
services:
  - rabbitmq
  - mongodb
install:
  - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update && sudo apt-get install yarn

before_script:
  - sudo rabbitmq-plugins enable rabbitmq_stomp
  - sudo service rabbitmq-server restart
  - sudo rabbitmqctl status
  - sudo rabbitmq-plugins list
script:
  - yarn
  - yarn build
  - yarn test
  - yarn lint
  - bash config/deployment/deploy.sh

cache:
  directories:
  - node_modules
git:
  depth: 3
after_script:
  - yarn report-coverage

#notifications:
#  slack: eliftech:rXNsG1csijJulkvTRPzVDU3w
