language: node_js

sudo: true
dist: trusty

node_js:
  - "4.6"
  - "6.9"
  - "7.2"
services:
  - rabbitmq
  - mongodb

cache:
  directories:
  - node_modules
git:
  depth: 3
after_script:
  - yarn report-coverage
